version: '3.3'
services:
  decadevs-docker:
    container_name: decadevs-docker-patience-itotojesu
    image: decadevs-docker-patience-itotojesu
    build: ./
    ports:
      - "8532:8080"
    expose:
      - "8532"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: patt
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: 123456
